_BASE_: "../Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN: ("combined_xview_instance_segmentation_dataset_train",)
  TEST: ("combined_xview_instance_segmentation_dataset_val",)
DATALOADER:
  NUM_WORKERS: 2
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1
  RESNETS:
    DEPTH: 50
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  MAX_ITER: 200000
OUTPUT_DIR: "./outputs/output_localization_02"
TEST:
  EVAL_PERIOD: 1000
